# Generated by Django 4.1.2 on 2023-10-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_category_article_nom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exemplaires_disponibles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='nom_maillot',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_maillot',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('livre', 'Livrée')], default='en_cours', max_length=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='taille',
            field=models.CharField(choices=[('X', 'X'), ('XL', 'XL'), ('XXL', 'XXL'), ('M', 'M')], default='null', max_length=3),
        ),
    ]
