# Generated by Django 4.1.2 on 2023-10-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_article_exemplaires_disponibles_commande_nom_maillot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero_maillot',
            field=models.CharField(default='null', max_length=3),
        ),
    ]
